NAME= ft_ls.out

SRCS=	./ft_add_cwd.c \
	./ft_copy_delete_args.c \
	./ft_diplay_format.c \
	./ft_fill_permisions.c \
	./ft_get_files_and_check_errors.c \
	./ft_get_options_and_check_errors.c \
	./ft_get_paths_and_check_errors.c \
	./ft_get_time_and_owner.c \
	./ft_list_directories.c \
	./ft_list_files.c \
	./ft_ls_sort_data.c \
	./ft_ls_sort_format.c \
	./ft_list_folder_long.c \
	./ft_loop_over_options.c \
	./ft_ls.c \
	./ft_ls_struct_utils.c \
	./ft_ls_struct_utils_two.c \
	./ft_ls_utils_one.c \
	./ft_ls_utils_two.c \
	./ft_print_dir_path_and_total.c \
	./ft_printf_utils.c \
	./ft_sort_by_time_long_n_elem.c \
	./ft_sort_by_time_short_all_data.c \
	./ft_sort_by_time_short_n_elem.c \
	./ft_start_listing.c 


FLAGS= -Werror -Wextra -Wall

all:
	gcc  -o ${NAME} ${SRCS}

fclean:
	/bin/rm -rf ${NAME}

