NAME= ft_ls.out

SRCS=	./ft_add_cwd.c \
	./ft_add_cwd_util.c \
	./ft_add_files.c \
	./ft_add_new_long_node_dir.c \
	./ft_add_new_node_long.c \
	./ft_calcule_column_padding.c \
	./ft_check_this_arg_is_valid_path.c \
	./ft_copy_and_count_args_opt.c \
	./ft_copy_delete_args.c \
	./ft_diplay_format.c \
	./ft_display_format_column.c \
	./ft_display_format_column_two.c \
	./ft_display_long_format.c \
	./ft_display_long_format_n_data.c \
	./ft_display_long_format_n_to_m_data.c \
	./ft_display_short_format.c \
	./ft_display_short_format_n_data.c \
	./ft_display_short_format_n_to_m_data.c \
	./ft_fill_permisions.c \
	./ft_free_data.c \
	./ft_free_data_util.c \
	./ft_get_files_and_check_errors.c \
	./ft_get_long_short_format_dir.c \
	./ft_get_long_short_format_files.c \
	./ft_get_long_short_format_folder.c \
	./ft_get_long_short_format_folder_at.c \
	./ft_get_options_and_check_errors.c \
	./ft_get_paths_and_check_errors.c \
	./ft_get_time_and_owner.c \
	./ft_iterate_recursion_long_format.c \
	./ft_iterate_recursion_short_format.c \
	./ft_list_dir.c \
	./ft_list_directories.c \
	./ft_list_directories_utils.c \
	./ft_list_files.c \
	./ft_list_folder_at_long.c \
	./ft_list_folder_at_short.c \
	./ft_list_folder_long_format.c \
	./ft_list_folder_short_format.c \
	./ft_loop_over_options.c \
	./ft_ls.c \
	./ft_ls_struct_utils.c \
	./ft_ls_utils_four.c \
	./ft_ls_utils_one.c \
	./ft_ls_utils_three.c \
	./ft_ls_utils_two.c \
	./ft_print_dir_path_and_total.c \
	./ft_printf_utils.c \
	./ft_push_back_long.c \
	./ft_push_back_short.c \
	./ft_set_exec_and_link_status.c \
	./ft_sort_all_data_short_long.c \
	./ft_sort_by_time_long_all_data.c \
	./ft_sort_by_time_long_n_elem.c \
	./ft_sort_by_time_long_n_to_m_elem.c \
	./ft_sort_by_time_short_all_data.c \
	./ft_sort_by_time_short_n_elem.c \
	./ft_sort_by_time_short_n_to_m_elem.c \
	./ft_sort_dirs_paths_by_time.c \
	./ft_sort_format_data_from_n_elem_long.c \
	./ft_sort_format_data_from_n_elem_short.c \
	./ft_sort_from_n_to_m_elem_long.c \
	./ft_sort_from_n_to_m_elem_short.c \
	./ft_start_listing.c

FLAGS= -Werror -Wextra -Wall

all:
	gcc $(FLAGS) -o ${NAME} ${SRCS}

fclean:
	/bin/rm -rf ${NAME}

