NAME= ft_ls.out

SRCS=	./ft_copy_delete_args.c \
	./ft_diplay_format.c \
	./ft_fill_permisions.c \
	./ft_get_files_and_check_errors.c \
	./ft_get_options_and_check_errors.c \
	./ft_get_paths_and_check_errors.c \
	./ft_get_time_and_owner.c \
	./ft_list_files.c \
	./ft_loop_over_options.c \
	./ft_ls.c \
	./ft_ls_struct_utils.c \
	./ft_ls_struct_utils_two.c \
	./ft_ls_utils_one.c \
	./ft_printf_utils.c \
	./ft_start_listing.c 


FLAGS= -Werror -Wextra -Wall

all:
	gcc $(FLAGS) -o ${NAME} ${SRCS}

fclean:
	/bin/rm -rf ${NAME}

